/**
 * Wire-format compatibility: the SDK (Web Crypto) must decrypt blobs produced by
 * backend/src/services/crypto.ts (Node crypto). The fixture at test/fixtures/crypto.json
 * is generated by scripts/gen-crypto-fixtures.mjs using the same Node primitives
 * as the backend — if this test fails, the SDK has diverged from the backend's
 * byte layout and will break cross-stack encryption.
 */
import { describe, expect, it } from 'vitest';
import fixture from './fixtures/crypto.json' with { type: 'json' };
import { aesDecrypt, eciesDecrypt } from '../src/crypto/index.js';

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return out;
}

describe('crypto cross-compat with backend wire format', () => {
  it('SDK decrypts backend-produced AES blob', async () => {
    const key = hexToBytes(fixture.aes.key);
    const blob = hexToBytes(fixture.aes.blob);
    const pt = await aesDecrypt(blob, key);
    expect(new TextDecoder().decode(pt)).toBe(fixture.plaintext);
  });

  it('SDK decrypts backend-produced ECIES blob', async () => {
    const blob = hexToBytes(fixture.ecies.blob);
    const pt = await eciesDecrypt(blob, fixture.keypair.privateKey);
    expect(new TextDecoder().decode(pt)).toBe(fixture.plaintext);
  });
});
